# Generated by Django 5.1 on 2025-10-31 01:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_id', models.UUIDField(db_index=True)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('event_type', models.CharField(max_length=30)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_data', models.JSONField(default=dict)),
            ],
        ),
    ]
